/* ITESS-TICS
 * Semestre Agosto-Diciembre 2023 
 * ANSYSC
 * Tema 2 Series de Fourier
 * By FJMP
 * 28/09/2023
 */
package fourier.transform;

import tools.*;
import java.awt.Color;
import java.awt.Graphics2D;

/**
 *
 * @author TICS03
 */
public class TransformadaDeFourierGUI extends javax.swing.JFrame {
    
    private Coordinate coordinateFw;
    private TFSample1 tf1;
    
    public TransformadaDeFourierGUI() {
        initComponents();
    }
    
    private void computeData(int wPoints){
        tf1 = new TFSample1(wPoints);
        
        tf1.computeW();
        tf1.computeFw();
    }
    
    private void drawPlots (){
        coordinateFw = new Coordinate(-2,2,-2,2,150,150);
        
        drawAxisFw();
        drawFunctionFw();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        plotFw = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnDraw = new javax.swing.JButton();
        lbNaprox = new javax.swing.JLabel();
        tfNAproximation = new javax.swing.JTextField();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        plotMod = new javax.swing.JPanel();
        plotPhase = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(0, 0, 0));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plotFw.setPreferredSize(new java.awt.Dimension(150, 150));
        plotFw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plotFwMouseClicked(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout plotFwLayout = new javax.swing.GroupLayout(plotFw);
        plotFw.setLayout(plotFwLayout);
        plotFwLayout.setHorizontalGroup(
            plotFwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotFwLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        plotFwLayout.setVerticalGroup(
            plotFwLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotFwLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        background.add(plotFw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, 120));

        btnDraw.setText("Draw");
        btnDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawActionPerformed(evt);
            }
        });
        background.add(btnDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        lbNaprox.setForeground(new java.awt.Color(255, 255, 255));
        lbNaprox.setText("N aproximation");
        background.add(lbNaprox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, -1));

        tfNAproximation.setText("1");
        tfNAproximation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNAproximationActionPerformed(evt);
            }
        });
        background.add(tfNAproximation, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 50, -1));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Tranformada de Fourier ASYS");
        background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Graficas de la transformada de Fourier para la función exponencial");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        plotMod.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout plotModLayout = new javax.swing.GroupLayout(plotMod);
        plotMod.setLayout(plotModLayout);
        plotModLayout.setHorizontalGroup(
            plotModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        plotModLayout.setVerticalGroup(
            plotModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        background.add(plotMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 260, 120));

        plotPhase.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout plotPhaseLayout = new javax.swing.GroupLayout(plotPhase);
        plotPhase.setLayout(plotPhaseLayout);
        plotPhaseLayout.setHorizontalGroup(
            plotPhaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        plotPhaseLayout.setVerticalGroup(
            plotPhaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        background.add(plotPhase, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 320, 120));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 490));

        setBounds(0, 0, 656, 488);
    }// </editor-fold>//GEN-END:initComponents

    private void drawAxisFw() {
        Graphics2D g = (Graphics2D) plotFw.getGraphics();
      
        g.setColor(new Color(50, 90, 20));
        g.fillRect(0,0, 300, 300);
        
        g.setColor(Color.white);
        
        // draw x axis, from  (XMIN,0) to  (XMAX, 0)  
        g.drawLine(
                coordinateFw.toScreenX(coordinateFw.getXMIN()),
                coordinateFw.toScreenY(0.0f),
                coordinateFw.toScreenX(coordinateFw.getXMAX()),
                coordinateFw.toScreenY(0.0f)
        );
        
        for (float dx = coordinateFw.getXMIN(); dx < coordinateFw.getXMAX(); dx += 1.0) {
            g.drawLine(
                coordinateFw.toScreenX(dx),
                coordinateFw.toScreenY(0),
                coordinateFw.toScreenX(dx),
                coordinateFw.toScreenY(0.5f)
            );
        }
        
        // draw y axis, from  (0,YMIN) to  (0, YMAX)  
        g.drawLine(
                coordinateFw.toScreenX(0.0f),
                coordinateFw.toScreenY(coordinateFw.getYMIN()),
                coordinateFw.toScreenX(0.00f),
                coordinateFw.toScreenY(coordinateFw.getYMAX())
        );
        
        for (float dy = coordinateFw.getYMIN(); dy < coordinateFw.getYMAX(); dy += 1.0) {
            g.drawLine(
                coordinateFw.toScreenX(0),
                coordinateFw.toScreenY(dy),
                coordinateFw.toScreenX(0.5f),
                coordinateFw.toScreenY(dy)
            );
        } 
    }
    
    private void drawFunctionFw() {
        ComplexNumber cn [] = tf1.getFw();
        float x[] = new float [cn.length];
        float y[] = new float [cn.length];
        
        for(int i = 0; i < cn.length; i++ ){
            x[i] = cn[i].getA();
            y[i] = cn[i].getB();
        }
      
        // Draw function points
         Graphics2D g = (Graphics2D) plotFw.getGraphics();
         g.setColor(Color.white);         
         for (int i = 0; i < x.length - 1; i++) {
             g.drawLine(
                coordinateFw.toScreenX(x[i]),
                coordinateFw.toScreenY(y[i]),
                coordinateFw.toScreenX(x[i+1]),
                coordinateFw.toScreenY(y[i+1])
            );
         }
    }
    
    private void drawAxisF() {
        Graphics2D g = (Graphics2D) background.getGraphics();
      
        g.setColor(new Color(50, 90, 20));
        g.fillRect(0,0, 300, 300);
        
        g.setColor(Color.white);
        
        // draw x axis, from  (0,0) to  (freqMAX, 0)
       
        g.drawLine(
                coordinateFw.toScreenX(coordinateFw.getXMIN()),
                coordinateFw.toScreenY(0.0f),
                coordinateFw.toScreenX(coordinateFw.getXMAX()),
                coordinateFw.toScreenY(0.0f)
        );
        
        for (float dx = coordinateFw.getXMIN(); dx < coordinateFw.getXMAX(); dx += 1.0) {
            g.drawLine(
                coordinateFw.toScreenX(dx),
                coordinateFw.toScreenY(0),
                coordinateFw.toScreenX(dx),
                coordinateFw.toScreenY(0.5f)
            );
        }
        
        // draw y axis, from  (0,YMIN) to  (0, YMAX)
       
        g.drawLine(
                coordinateFw.toScreenX(0.0f),
                coordinateFw.toScreenY(coordinateFw.getYMIN()),
                coordinateFw.toScreenX(0.00f),
                coordinateFw.toScreenY(coordinateFw.getYMAX())
        );
        
        for (float dy = coordinateFw.getYMIN(); dy < coordinateFw.getYMAX(); dy += 1.0) {
            g.drawLine(
                coordinateFw.toScreenX(0),
                coordinateFw.toScreenY(dy),
                coordinateFw.toScreenX(0.5f),
                coordinateFw.toScreenY(dy)
            );
        } 
    }
    
     
         
    
    
    private void plotFwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plotFwMouseClicked
        // TODO add your handling code here:
       draw();
    }//GEN-LAST:event_plotFwMouseClicked

    private void draw() {
     int wPoints =  Integer.parseInt( 
                tfNAproximation.getText()
            );
       computeData (wPoints);
       drawPlots ();
    }
    
    private void btnDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawActionPerformed
        // TODO add your handling code here:
        draw();
    }//GEN-LAST:event_btnDrawActionPerformed

    private void tfNAproximationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNAproximationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNAproximationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransformadaDeFourierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransformadaDeFourierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransformadaDeFourierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransformadaDeFourierGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransformadaDeFourierGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnDraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNaprox;
    private javax.swing.JPanel plotFw;
    private javax.swing.JPanel plotMod;
    private javax.swing.JPanel plotPhase;
    private javax.swing.JTextField tfNAproximation;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
